name: Webpack打包构建
on:
  workflow_call:
    inputs:
      buildArg:
        required: false
        type: string
      dockerBuildMode:
        required: true
        type: string
      kubectlRelease:
        required: true
        type: string
    secrets:
      qiniuAccessKey:
        required: true
      qiniuBucket:
        required: true
      qiniuScecretKey:
        required: true
      kubeConfig:
        required: true
      sshKey:
        required: true
      dockerPassword:
        required: true
jobs:
  buildAndDeploy:
    name: Webpack打包构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ssh-key: "${{ secrets.sshKey }}"
      - name: 设置node环境版本
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "14"
          cache: "npm"
      - name: 输出全局变量-版本号
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Webpack构建
        run: ./build.sh -v ${{ steps.vars.outputs.tag }} ${{ inputs.buildArg }}
      - name: 上传到CDN
        run: |
          curl -SsO https://morphinewan.github.io/tools/qnsync
          chmod +x qnsync
          ./qnsync -ak $QINIU_ACCESS_KEY -sk $QINIU_SECRET_KEY -bk $QINIU_BUCKET $GITHUB_WORKSPACE/$SYNC_PATH
        env:
          QINIU_ACCESS_KEY: ${{ secrets.qiniuAccessKey }}
          QINIU_BUCKET: ${{ secrets.qiniuBucket }}
          QINIU_SECRET_KEY: ${{ secrets.qiniuScecretKey }}
          SYNC_PATH: dist
      - name: 推送镜像到GitHub Packages
        uses: ./.github/actions/docker
        env:
          BUILD_MODE: ${{ inputs.dockerBuildMode }}
          DOCKER_PASSWORD: ${{ secrets.dockerPassword }}
      - uses: ./.github/actions/kubectl
        name: 更新K8S
        env:
          VERSION: ${{ steps.vars.outputs.tag }}
          RELEASE: ${{ inputs.kubectlRelease }}
        with:
          KUBECONFIG: ${{ secrets.kubeConfig }}
