name: Webpack打包构建
on:
  workflow_call:
    inputs:
      buildArg:
        required: false
        type: string
      refreshUrls:
        required: true
        type: string
    secrets:
      qiniuAccessKey:
        required: true
      qiniuBucket:
        required: true
      qiniuScecretKey:
        required: true
      sshKey:
        required: true
jobs:
  buildAndDeploy:
    name: Webpack打包构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ssh-key: "${{ secrets.sshKey }}"
      - name: 设置node环境版本
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "14"
          cache: "npm"
      - name: 输出全局变量-版本号
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Webpack构建
        run: ./build.sh -v ${{ steps.vars.outputs.tag }} ${{ inputs.buildArg }}
      - name: 上传到CDN
        run: |
          curl -SsO https://morphinewan.github.io/tools/qnsync
          chmod +x qnsync
          ./qnsync -force -ak $QINIU_ACCESS_KEY -sk $QINIU_SECRET_KEY -bk $QINIU_BUCKET $GITHUB_WORKSPACE/$SYNC_PATH
        env:
          QINIU_ACCESS_KEY: ${{ secrets.qiniuAccessKey }}
          QINIU_BUCKET: ${{ secrets.qiniuBucket }}
          QINIU_SECRET_KEY: ${{ secrets.qiniuScecretKey }}
          SYNC_PATH: dist
      - name: 刷新CDN缓存
        run: |
          curl -SsO https://devtools.qiniu.com/qshell-v2.9.0-linux-amd64.tar.gz
          tar -xf qshell-v2.9.0-linux-amd64.tar.gz
          chmod +x qshell
          ./qshell account $QINIU_ACCESS_KEY $QINIU_SECRET_KEY keyu
          echo -e "${{ inputs.refreshUrls }}" > torefresh.txt
          ./qshell cdnrefresh -i torefresh.txt
        env:
          QINIU_ACCESS_KEY: ${{ secrets.qiniuAccessKey }}
          QINIU_SECRET_KEY: ${{ secrets.qiniuScecretKey }}