name: Unit Test
on: workflow_call
jobs:
  unitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置node环境版本12.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "14"
          cache: "npm"
      - name: Lint & Test
        run: |
          npm install
          npm run lint
          npm run test
