name: Unit Test
on: workflow_call
jobs:
  unitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 设置node环境版本12.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "14"
      - name: 获取npm缓存目录
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: 缓存npm安装模块
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Lint & Test
        run: |
          npm install
          npm run lint
          npm run test
